const lang = {
  en: {
    lookStraightText: "Look straight",
    moveCloserText: "Move Closer",
    moveAwayText: "Move Away",
    holdStillText: "Hold Still",
    frameFaceText: "Place your face in frame",
    faceVerificationFailedText:
      "Unfortunately, your face recognition is failed. Please try again.",
    exceptionText: "Something went wrong.",
	exceptionDocumentText: "Please take a document photo again.",
    notVerifiedText: "Not Verified",
    failedText: "Failed",
    verifiedText: "Verified",
    passportScanText: "Passport scan",
    idScanText: "Front Side",
    passportScanDescText: "Scan the data page of passport",
    idScanDescText: "Scan the front side of the document",
	uploadoppositeText: "Upload the opposite side of the document",
    oppositeText: "Scan the opposite side of the document",
    selfieText: "Selfie",
    makeSelfieText: "Make selfie",
    oppositeSideText: "Opposite Side",
    takePhotoBtnText: "Take a photo",
    passportText: "PASSPORT",
    idCardText: "ID CARD",
    orText: "OR",
    uploadSecondPageText: "Upload back side",
    captureBtnText: "Capture",
    uploadFirstPageText: "Upload a photo",
  },
};
